services:
  - type: web
    name: pip-water
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.4
      - key: EMAIL_ENABLED
        value: true
      - key: EMAIL_BACKEND
        value: brevo
      - key: RUN_SEND_EMAIL_DEFAULT
        value: true